# This tells Netlify how to build your project.
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# This is the crucial rule that fixes the "Page not found" error.
# It tells Netlify to redirect all paths to index.html so React can handle routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
